name: gp-torch
channels:
  - pytorch
  - defaults
dependencies:
  - ipykernel
  - ipython
  - joblib
  - jupyter_client
  - jupyter_core
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - numpy-base
  - pandas
  - pip
  - python
  - pytorch=1.10.2
  - scipy
  - seaborn
  - pip:
    - gpytorch==1.8.0
    - lvgp-pytorch==0.1.1
    - numpy==1.20.0
    - scikit-learn==1.0.2
    - threadpoolctl==3.1.0
    - torch==1.10.0
