name: gp-torch
channels:
  - pytorch
  - defaults
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - fonttools=4.25.0
  - freetype=2.10.4
  - icu=58.2
  - ipykernel=6.4.1
  - ipython=7.31.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kiwisolver=1.4.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - munkres=1.1.4
  - nest-asyncio=1.5.5
  - numexpr=2.8.3
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - prompt-toolkit=3.0.20
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyzmq=23.2.0
  - qt=5.9.7
  - scipy=1.7.3
  - seaborn=0.11.2=
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - gpytorch==1.8.0
    - lvgp-pytorch==0.1.1
    - numpy==1.20.0
    - scikit-learn==1.0.2
    - threadpoolctl==3.1.0
    - torch==1.10.0
